#!/usr/bin/env python
import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
import cv2
import numpy as np


def image_callback(msg):
    bridge = CvBridge()
    try:
        # Convert the ROS Image message to OpenCV2 format
        # Use "passthrough" to keep the depth image format
        cv_image = bridge.imgmsg_to_cv2(msg, "passthrough")
    except CvBridgeError as e:
        print(e)
    else:
        # Normalize the depth image to display it
        cv_image_normalized = cv2.normalize(cv_image, None, 0, 1, cv2.NORM_MINMAX)

        # Display the image with OpenCV
        cv2.imshow("Depth Image window", cv_image_normalized)
        cv2.waitKey(3)


def main():
    rospy.init_node('depth_image_display_node', anonymous=True)
    image_topic = "/camera/depth/image_raw"  # The depth image topic from Gazebo
    rospy.Subscriber(image_topic, Image, image_callback)
    rospy.spin()


if __name__ == '__main__':
    main()
